name: Deploy to GitHub Pages

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout the repository
                uses: actions/checkout@v2

            -   name: Setup Node.js
                uses: actions/setup-node@v2
                with:
                    node-version: 20

            -   name: Setup pnpm
                run: npm install -g pnpm

            -   name: Create env file
                run: |
                    touch .env
                    echo PORTFOLIO_NUXT_APP_BASE_URL=${{ vars.PORTFOLIO_NUXT_APP_BASE_URL }} >> .env
                    echo SHOPPING_LIST_NUXT_APP_BASE_URL=${{ vars.SHOPPING_LIST_NUXT_APP_BASE_URL }} >> .env
                    echo SHOPPING_LIST_SUPABASE_URL=${{ vars.SHOPPING_LIST_SUPABASE_URL }} >> .env
                    echo SHOPPING_LIST_SUPABASE_KEY=${{ vars.SHOPPING_LIST_SUPABASE_KEY }} >> .env
                    cat .env

            -   name: Install dependencies
                run: pnpm install

            -   name: Build Shopping List
                run: pnpm shopping-list:build:gh:pages

            -   name: Deploy Shopping List to GitHub Pages
                uses: peaceiris/actions-gh-pages@v3
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    publish_dir: ./apps/shopping-list/.output/public
                    destination_dir: shopping-list

            -   name: Build apps
                run: pnpm build:gh-pages

            -   name: Deploy Portfolio to GitHub Pages
                uses: peaceiris/actions-gh-pages@v3
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    publish_dir: ./apps/portfolio/.output/public

            -   name: Deploy Shopping List to GitHub Pages
                uses: peaceiris/actions-gh-pages@v3
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    publish_dir: ./apps/shopping-list/.output/public
                    destination_dir: shopping-list
