# https://github.com/actions/deploy-pages#usage
name: Deploy to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - run: corepack prepare pnpm@latest --activate
      - uses: pnpm/action-setup@v2
        with:
          node-version: "20"
          cache: "pnpm"
      - name: "Create env file"
        run: |
              touch .env
              echo SHOPPING_LIST_NUXT_APP_BASE_URL=${{ vars.SHOPPING_LIST_NUXT_APP_BASE_URL }} >> .env
              echo SHOPPING_LIST_SUPABASE_URL=${{ vars.SHOPPING_LIST_SUPABASE_URL }} >> .env
              echo SHOPPING_LIST_SUPABASE_KEY=${{ vars.SHOPPING_LIST_SUPABASE_KEY }} >> .env
              cat .env
      # Pick your own package manager and build script
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm build:gh-pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./apps/shopping-list/.output/public
  # Deployment job
  deploy:
    # Add a dependency to the build job
    needs: build
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    # Deploy to the github_pages environment
    environment:
      name: github_pages
      url: ${{ steps.deployment.outputs.page_url }}
    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
